# osgQt .pc filename change all the time.
macro(ADD_OSGQT_DEPENDENCY)
  set(OSGQT_DEPENDENCY openscenegraph-osgQt)
  find_package(${OSGQT_DEPENDENCY} QUIET)
  if(${OSGQT_DEPENDENCY}_FOUND)
    add_required_dependency(${OSGQT_DEPENDENCY})
  else()
    set(OSGQT_DEPENDENCY openscenegraph-osgQt6)
    find_package(${OSGQT_DEPENDENCY} QUIET)
    if(${OSGQT_DEPENDENCY}_FOUND)
      add_required_dependency(${OSGQT_DEPENDENCY})
    else()
      set(OSGQT_DEPENDENCY openscenegraph-osgQt5)
      add_required_dependency(${OSGQT_DEPENDENCY})
    endif()
  endif()
endmacro(ADD_OSGQT_DEPENDENCY)
